cton – FLAP
cton Interface
Source File
public interface cton
Procedure for converting string to number, real or initeger, (string to number type casting).
Calls
Called By
Module Procedures
private function ctor_R8P(pref, error, str, knd) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag: 0 no errors, >0 error occurs.
character(len=*), intent(in) :: str
String containing input number.
real(kind=R8P), intent(in) :: knd
Number kind.
Return Value real(kind=R8P)
Number returned.
Description
Procedure for converting string to real. This function achieves casting of string to real.
private function ctor_R4P(pref, error, str, knd) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag: 0 no errors, >0 error occurs.
character(len=*), intent(in) :: str
String containing input number.
real(kind=R4P), intent(in) :: knd
Number kind.
Return Value real(kind=R4P)
Number returned.
Description
Procedure for converting string to real. This function achieves casting of string to real.
private function ctoi_I8P(pref, error, str, knd) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag: 0 no errors, >0 error occurs.
character(len=*), intent(in) :: str
String containing input number.
integer(kind=I8P), intent(in) :: knd
Number kind.
Return Value integer(kind=I8P)
Number returned.
Description
Procedure for converting string to integer. This function achieves casting of string to integer.
private function ctoi_I4P(pref, error, str, knd) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag: 0 no errors, >0 error occurs.
character(len=*), intent(in) :: str
String containing input number.
integer(kind=I4P), intent(in) :: knd
Number kind.
Return Value integer(kind=I4P)
Number returned.
Description
Procedure for converting string to integer. This function achieves casting of string to integer.
private function ctoi_I2P(pref, error, str, knd) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag: 0 no errors, >0 error occurs.
character(len=*), intent(in) :: str
String containing input number.
integer(kind=I2P), intent(in) :: knd
Number kind.
Return Value integer(kind=I2P)
Number returned.
Description
Procedure for converting string to integer. This function achieves casting of string to integer.
private function ctoi_I1P(pref, error, str, knd) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag: 0 no errors, >0 error occurs.
character(len=*), intent(in) :: str
String containing input number.
integer(kind=I1P), intent(in) :: knd
Number kind.
Return Value integer(kind=I1P)
Number returned.
Description
Procedure for converting string to integer. This function achieves casting of string to integer.
Call graph
cton calls ctoi_i1p, ctoi_i8p, ctor_r8p, ctoi_i2p, ctoi_i4p, ctor_r4p
get_cla_list_varying_i4p calls cton
get_cla_list_varying_i1p calls cton
get_cla_list_from_buffer calls cton
get_cla_list_varying_i8p calls cton
get_cla_list_varying_i2p calls cton
signature calls cton
get_cla_list_varying_r4p calls cton
get_cla_from_buffer calls cton
get_cla_list_varying_r8p calls cton
usage calls cton
test_driver calls cton
parse calls cton
get_cla_list_varying_r16p calls cton
check_choices calls cton