ctoi_I1P – FLAP
ctoi_I1P Function
17 statements
Source File
private function ctoi_I1P(str, knd, pref, error) result(n)
Convert string to integer.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
String containing input number.
integer(kind=I1P), intent(in) :: knd
Number kind.
character(len=*), intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag: 0 no errors, >0 error occurs.
Return Value integer(kind=I1P)
Number returned.
Called By
Source Code
ctoi_I1P
Source Code
  function ctoi_I1P(str, knd, pref, error) result(n)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Convert string to integer.
  !---------------------------------------------------------------------------------------------------------------------------------
  character(*),           intent(in)  :: str   !< String containing input number.
  integer(I1P),           intent(in)  :: knd   !< Number kind.
  character(*), optional, intent(in)  :: pref  !< Prefixing string.
  integer(I4P), optional, intent(out) :: error !< Error trapping flag: 0 no errors, >0 error occurs.
  integer(I1P)                        :: n     !< Number returned.
  integer(I4P)                        :: err   !< Error trapping flag: 0 no errors, >0 error occurs.
  character(len=:), allocatable       :: prefd !< Prefixing string.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  read(str, *, iostat=err) n ! Casting of str to n.
  if (err/=0) then
    prefd = '' ; if (present(pref)) prefd = pref
    write(stderr, '(A,I1,A)') prefd//' Error: conversion of string "'//str//'" to integer failed! integer(', kind(knd), ')'
  endif
  if (present(error)) error = err
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction ctoi_I1P
All Procedures
add add add_group assign_object bctoi_I1P bctoi_I2P bctoi_I4P bctoi_I8P bcton bctor_R16P bctor_R4P bctor_R8P bit_size bit_size bit_size_chr bit_size_R16P bit_size_R4P bit_size_R8P bstr bstr_I1P bstr_I2P bstr_I4P bstr_I8P bstr_R16P bstr_R4P bstr_R8P byte_size byte_size_chr byte_size_I1P byte_size_I2P byte_size_I4P byte_size_I8P byte_size_R16P byte_size_R4P byte_size_R8P check check check check_action_consistency check_choices check_endian check_envvar_consistency check_list_size check_m_exclude_consistency check_m_exclusive check_m_exclusive check_named_consistency check_optional_consistency check_positional_consistency cla_assign_cla clasg_assign_clasg cli_assign_cli compact_real_string count count_substring ctoi_I1P ctoi_I2P ctoi_I4P ctoi_I8P cton ctor_R16P ctor_R4P ctor_R8P digit digit_I1 digit_I2 digit_I4 digit_I8 errored errored errored finalize finalize finalize free free free free_object get_args_from_invocation get_args_from_string get_cla get_cla get_cla_from_buffer get_cla_list get_cla_list get_cla_list_from_buffer get_cla_list_varying_char get_cla_list_varying_char get_cla_list_varying_I1P get_cla_list_varying_I1P get_cla_list_varying_I2P get_cla_list_varying_I2P get_cla_list_varying_I4P get_cla_list_varying_I4P get_cla_list_varying_I8P get_cla_list_varying_I8P get_cla_list_varying_logical get_cla_list_varying_logical get_cla_list_varying_R16P get_cla_list_varying_R16P get_cla_list_varying_R4P get_cla_list_varying_R4P get_cla_list_varying_R8P get_cla_list_varying_R8P get_clasg_indexes init is_called_group is_defined is_defined is_defined_group is_parsed is_passed is_passed is_required_passed is_required_passed parse parse penf_init penf_print print_error_message print_usage print_version raise_error_m_exclude raise_error_m_exclude raise_error_nargs_insufficient raise_error_switch_unknown raise_error_value_missing replace replace_all sanitize_defaults sanitize_defaults save_man_page save_usage_to_markdown set_mutually_exclusive_groups signature signature signature str str_a_I1P str_a_I2P str_a_I4P str_a_I8P str_a_R16P str_a_R4P str_a_R8P str_bol str_I1P str_I2P str_I4P str_I8P str_R16P str_R4P str_R8P strf_I1P strf_I2P strf_I4P strf_I8P strf_R16P strf_R4P strf_R8P strz strz_I1P strz_I2P strz_I4P strz_I8P tokenize unique upper_case usage usage usage wstrip
Call graph
cton calls ctoi_i1p
signature calls cton
parse calls cton
get_cla_from_buffer calls cton
get_cla_list_varying_r8p calls cton
get_cla_list_varying_i8p calls cton
usage calls cton
get_cla_list_varying_i1p calls cton
get_cla_list_varying_i2p calls cton
check_choices calls cton
get_cla_list_from_buffer calls cton
test_all calls cton
get_cla_list_varying_r16p calls cton
get_cla_list_varying_i4p calls cton
get_cla_list_varying_r4p calls cton