str_I4P – FLAP
str_I4P Function
Source File
private elemental function str_I4P(no_sign, n) result(str)
Arguments
Type Intent Optional Attributes Name
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
integer(kind=I4P), intent(in) :: n
Integer to be converted.
Return Value character(len=DI4P)
Returned string containing input number plus padding zeros.
Description
Procedure for converting integer to string. This function achieves casting of integer to string.
Called By
Source Code
  elemental function str_I4P(no_sign,n) result(str)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Procedure for converting integer to string. This function achieves casting of integer to string.
  !---------------------------------------------------------------------------------------------------------------------------------
  implicit none
  logical,      intent(IN), optional:: no_sign !< Flag for leaving out the sign.
  integer(I4P), intent(IN)::           n       !< Integer to be converted.
  character(DI4P)::                    str     !< Returned string containing input number plus padding zeros.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  write(str,FI4P) n                 ! Casting of n to string.
  str = adjustl(trim(str))          ! Removing white spaces.
  if (n>=0_I4P) str='+'//trim(str)  ! Prefixing plus if n>0.
  if (present(no_sign)) str=str(2:) ! Leaving out the sign.
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction str_I4P
Call graph
str_a_i4p calls str_i4p
str calls str_i4p, str_a_i4p
errored calls str
bctoi_i8p calls str
test_choices_logical calls str
test_hidden calls str
signature calls str
bctoi_i1p calls str
bctoi_i4p calls str
usage calls str
bctor_r4p calls str
test_nested calls str
check_choices calls str
test_basic calls str
test_driver calls str, bcton
test_string calls str
bctoi_i2p calls str
bctor_r8p calls str
bcton calls bctoi_i8p, bctoi_i1p, bctoi_i4p, bctor_r4p, bctoi_i2p, bctor_r8p