str_a_I4P – FLAP
str_a_I4P Function
27 statements
Source File
private pure function str_a_I4P(n, no_sign, separator, delimiters) result(str)
Convert integer array to string.
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: n(:)
Integer array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=1), intent(in), optional :: separator
Eventual separator of array values.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
Return Value character(len=:), allocatable
Returned string containing input number.
Calls
Called By
Source Code
str_a_I4P
Source Code
  pure function str_a_I4P(n, no_sign, separator, delimiters) result(str)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Convert integer array to string.
  !---------------------------------------------------------------------------------------------------------------------------------
  integer(I4P), intent(in)           :: n(:)            !< Integer array to be converted.
  logical,      intent(in), optional :: no_sign         !< Flag for leaving out the sign.
  character(1), intent(in), optional :: separator       !< Eventual separator of array values.
  character(*), intent(in), optional :: delimiters(1:2) !< Eventual delimiters of array values.
  character(len=:), allocatable      :: str             !< Returned string containing input number.
  character(DI4P)                    :: strn            !< String containing of element of input array number.
  character(len=1)                   :: sep             !< Array values separator
  integer                            :: i               !< Counter.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  str = ''
  sep = ','
  if(present(separator)) sep = separator
  if (present(no_sign)) then
    do i=1,size(n)
      strn = str_I4P(no_sign=no_sign, n=n(i))
      str = str//sep//trim(strn)
    enddo
  else
    do i=1,size(n)
      strn = str_I4P(n=n(i))
      str = str//sep//trim(strn)
    enddo
  endif
  str = trim(str(2:))
  if (present(delimiters)) str = delimiters(1)//str//delimiters(2)
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction str_a_I4P
All Procedures
add add add_group assert_close_r32 assert_close_r32_1 assert_close_r64 assert_close_r64_1 assert_equal_i16 assert_equal_i16_1 assert_equal_i32 assert_equal_i32_1 assert_equal_i64 assert_equal_i64_1 assert_equal_i8 assert_equal_i8_1 assert_equal_l assert_equal_l_1 assert_equal_r32 assert_equal_r32_1 assert_equal_r64 assert_equal_r64_1 assert_positive_i16 assert_positive_i16_1 assert_positive_i32 assert_positive_i32_1 assert_positive_i64 assert_positive_i64_1 assert_positive_i8 assert_positive_i8_1 assert_positive_r32 assert_positive_r32_1 assert_positive_r64 assert_positive_r64_1 assign_object bctoi_I1P bctoi_I2P bctoi_I4P bctoi_I8P bcton bctor_R16P bctor_R4P bctor_R8P bit_size bit_size bit_size_chr bit_size_R16P bit_size_R4P bit_size_R8P bstr bstr_I1P bstr_I2P bstr_I4P bstr_I8P bstr_R16P bstr_R4P bstr_R8P byte_size byte_size_chr byte_size_I1P byte_size_I2P byte_size_I4P byte_size_I8P byte_size_R16P byte_size_R4P byte_size_R8P check check check check_action_consistency check_choices check_endian check_envvar_consistency check_list_size check_m_exclude_consistency check_m_exclusive check_m_exclusive check_named_consistency check_optional_consistency check_positional_consistency cla_assign_cla clasg_assign_clasg cli_assign_cli color_index colorize colors_samples compact_real_string count count_substring ctoi_I1P ctoi_I2P ctoi_I4P ctoi_I8P cton ctor_R16P ctor_R4P ctor_R8P digit digit_I1 digit_I2 digit_I4 digit_I8 errored errored errored fake_call finalize finalize finalize free free free free_object get_args_from_invocation get_args_from_string get_cla get_cla get_cla_from_buffer get_cla_list get_cla_list get_cla_list_from_buffer get_cla_list_varying_char get_cla_list_varying_char get_cla_list_varying_I1P get_cla_list_varying_I1P get_cla_list_varying_I2P get_cla_list_varying_I2P get_cla_list_varying_I4P get_cla_list_varying_I4P get_cla_list_varying_I8P get_cla_list_varying_I8P get_cla_list_varying_logical get_cla_list_varying_logical get_cla_list_varying_R16P get_cla_list_varying_R16P get_cla_list_varying_R4P get_cla_list_varying_R4P get_cla_list_varying_R8P get_cla_list_varying_R8P get_clasg_indexes init init is_called_group is_defined is_defined is_defined_group is_parsed is_passed is_passed is_required_passed is_required_passed parse parse penf_init penf_print print print_error_message print_usage print_version raise_error_m_exclude raise_error_m_exclude raise_error_nargs_insufficient raise_error_switch_unknown raise_error_value_missing replace replace_all sanitize_defaults sanitize_defaults save_man_page save_usage_to_markdown set_mutually_exclusive_groups signature signature signature str str_a_I1P str_a_I2P str_a_I4P str_a_I8P str_a_R16P str_a_R4P str_a_R8P str_bol str_I1P str_I2P str_I4P str_I8P str_R16P str_R4P str_R8P strf_I1P strf_I2P strf_I4P strf_I8P strf_R16P strf_R4P strf_R8P strz strz_I1P strz_I2P strz_I4P strz_I8P style_index styles_samples tokenize unique upper upper_case usage usage usage wstrip
Call graph
str_a_i4p calls str_i4p
str calls str_a_i4p
errored calls str
flap_test_choices_logical calls str
test_all calls str, bcton
check_choices calls str
signature calls str
flap_test_string calls str
flap_test_hidden calls str
bctor_r4p calls str
flap_test_nested calls str
flap_test_basic calls str
usage calls str
bctoi_i2p calls str
compact_real calls str
bctoi_i1p calls str
bctoi_i4p calls str
bctoi_i8p calls str
bctor_r8p calls str
bctor_r16p calls str
bcton calls bctor_r4p, bctoi_i2p, bctoi_i1p, bctoi_i4p, bctoi_i8p, bctor_r8p