tokenize – FLAP
tokenize Subroutine
Source File
public pure subroutine tokenize(strin, delimiter, toks, Nt)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: strin
String to be tokenized.
character(len=*), intent(in) :: delimiter
Delimiter of tokens.
character(len=len(strin)), intent(out), allocatable :: toks(:)
Tokens.
integer(kind=I4P), intent(out), optional :: Nt
Number of tokens.
Description
Tokenize a string in order to parse it.
Note
The dummy array containing tokens must allocatable and its character elements must have the same length of the input string. If the length of the delimiter is higher than the input string one then the output tokens array is allocated with only one element set to input string.
Called By
Variables
Type Visibility Attributes Name Initial
character(len=len(strin)), public :: strsub
Temporary string.
integer(kind=I4P), public :: dlen
Delimiter length.
integer(kind=I4P), public :: c
Counter.
integer(kind=I4P), public :: n
Counter.
integer(kind=I4P), public :: t
Counter.
Source Code
  pure subroutine tokenize(strin, delimiter, toks, Nt)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Tokenize a string in order to parse it.
  !<
  !< @note The dummy array containing tokens must allocatable and its character elements must have the same length of the input
  !< string. If the length of the delimiter is higher than the input string one then the output tokens array is allocated with
  !< only one element set to input string.
  !---------------------------------------------------------------------------------------------------------------------------------
  character(len=*),          intent(in)               :: strin     !< String to be tokenized.
  character(len=*),          intent(in)               :: delimiter !< Delimiter of tokens.
  character(len=len(strin)), intent(out), allocatable :: toks(:)   !< Tokens.
  integer(I4P),              intent(out), optional    :: Nt        !< Number of tokens.
  character(len=len(strin))                           :: strsub    !< Temporary string.
  integer(I4P)                                        :: dlen      !< Delimiter length.
  integer(I4P)                                        :: c         !< Counter.
  integer(I4P)                                        :: n         !< Counter.
  integer(I4P)                                        :: t         !< Counter.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  ! initialization
  if (allocated(toks)) deallocate(toks)
  strsub = strin
  dlen = len(delimiter)
  if (dlen>len(strin)) then
    allocate(toks(1:1)) ; toks(1) = strin ; if (present(Nt)) Nt = 1 ; return
  endif
  ! compute the number of tokens
  n = 1
  do c=1,len(strsub)-dlen ! loop over string characters
    if (strsub(c:c+dlen-1)==delimiter) n = n + 1
  enddo
  allocate(toks(1:n))
  ! tokenization
  do t=1,n ! loop over tokens
    c = index(strsub, delimiter)
    if (c>0) then
      toks(t) = strsub(1:c-1)
      strsub = strsub(c+dlen:)
    else
      toks(t) = strsub
    endif
  enddo
  if (present(Nt)) Nt = n
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine tokenize
Call graph
get_cla_list calls tokenize
get_cla_list_varying_i4p calls tokenize
get_cla_list_varying_i1p calls tokenize
get_cla_list_varying_r16p calls tokenize
get_cla_list_varying_logical calls tokenize
get_cla_list_varying_i8p calls tokenize
get_cla_list_varying_char calls tokenize
get_cla_list_varying_r4p calls tokenize
get_cla_list_varying_r8p calls tokenize
get_cla_list_varying_i2p calls tokenize
get_args_from_string calls tokenize, sanitize_args
check_choices calls tokenize
get_cla_list_from_buffer calls tokenize