usage – FLAP
usage Function
113 statements
Source File
private function usage(self, pref, markdown)
Get correct usage.
Arguments
Type Intent Optional Attributes Name
class(command_line_argument), intent(in) :: self
CLAs group data.
character(len=*), intent(in), optional :: pref
Prefixing string.
logical, intent(in), optional :: markdown
Format for markdown
Return Value character(len=:), allocatable
Usage string.
Calls
Source Code
usage
Source Code
  function usage(self, pref, markdown)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Get correct usage.
  !---------------------------------------------------------------------------------------------------------------------------------
  class(command_line_argument), intent(in) :: self      !< CLAs group data.
  character(*), optional,       intent(in) :: pref      !< Prefixing string.
  logical,      optional,       intent(in) :: markdown  !< Format for markdown
  character(len=:), allocatable            :: usage     !< Usage string.
  character(len=:), allocatable            :: prefd     !< Prefixing string.
  integer(I4P)                             :: a         !< Counter.
  logical                                  :: markdownd !< Format for markdown
  integer                                  :: indent    !< how many spaces to indent
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  markdownd = .false. ; if (present(markdown)) markdownd = markdown
  indent = 4
  if (.not.self%is_hidden) then
    if (self%act==action_store) then
      if (.not.self%is_positional) then
        if (allocated(self%nargs)) then
          usage = ''
          select case(self%nargs)
          case('+')
            usage = usage//' value#1 [value#2...]'
          case('*')
            usage = usage//' [value#1 value#2...]'
          case default
            do a=1, cton(str=trim(adjustl(self%nargs)),knd=1_I4P)
              usage = usage//' value#'//trim(str(a, .true.))
            enddo
          endselect
          if (trim(adjustl(self%switch))/=trim(adjustl(self%switch_ab))) then
            if (markdownd) then
              usage = new_line('a')//'* `'//trim(adjustl(self%switch))//usage//'`, `'//trim(adjustl(self%switch_ab))//usage//'`'
            else
              usage = '   '//trim(adjustl(self%switch))//usage//', '//trim(adjustl(self%switch_ab))//usage
            endif
          else
            if (markdownd) then
              usage = new_line('a')//'* `'//trim(adjustl(self%switch))//usage//'`'
            else
              usage = '   '//trim(adjustl(self%switch))//usage
            endif
          endif
        else
          if (trim(adjustl(self%switch))/=trim(adjustl(self%switch_ab))) then
            if (markdownd) then
              usage = new_line('a')//'* `'//trim(adjustl(self%switch))//' value`, `'//trim(adjustl(self%switch_ab))//' value'//'`'
            else
              usage = '   '//trim(adjustl(self%switch))//' value, '//trim(adjustl(self%switch_ab))//' value'
            endif
          else
            if (markdownd) then
              usage = new_line('a')//'* `'//trim(adjustl(self%switch))//' value`'
            else
              usage = '   '//trim(adjustl(self%switch))//' value'
            endif
          endif
        endif
      else
        usage = '  value'
      endif
      if (allocated(self%choices)) then
        usage = usage//', value in: `'//self%choices//'`'
      endif
    elseif (self%act==action_store_star) then
      usage = '  [value]'
      if (allocated(self%choices)) then
        usage = usage//', value in: ('//self%choices//')'
      endif
    else
      if (trim(adjustl(self%switch))/=trim(adjustl(self%switch_ab))) then
        if (markdownd) then
          usage = new_line('a')//'* `'//trim(adjustl(self%switch))//'`, `'//trim(adjustl(self%switch_ab))//'`'
        else
          usage = '   '//trim(adjustl(self%switch))//', '//trim(adjustl(self%switch_ab))
        endif
      else
        if (markdownd) then
          usage = new_line('a')//'* `'//trim(adjustl(self%switch))//'`'
        else
          usage = '   '//trim(adjustl(self%switch))
        endif
      endif
    endif
    prefd = '' ; if (present(pref)) prefd = pref
    usage = prefd//usage
    if (self%is_positional) usage = usage//new_line('a')//prefd//repeat(' ',indent)//trim(str(self%position, .true.))//&
      '-th argument'
    if (allocated(self%envvar)) then
      if (self%envvar /= '') then
        usage = usage//new_line('a')//prefd//repeat(' ',10)//'environment variable name "'//trim(adjustl(self%envvar))//'"'
      endif
    endif
    if (.not.self%is_required) then
      if (self%def /= '') then
        if (markdownd) then
          ! two spaces make a line break in markdown.
          usage = usage//'  '//new_line('a')//prefd//repeat(' ', 4)//'default value '//trim(replace_all(self%def,ARGS_SEP,' '))
        else
          usage = usage//new_line('a')//prefd//repeat(' ', indent)//'default value '//trim(replace_all(self%def,ARGS_SEP,' '))
        endif
      endif
    endif
    if (self%m_exclude/='') usage = usage//new_line('a')//prefd//repeat(' ', indent)//'mutually exclude "'//self%m_exclude//'"'
    if (markdownd) then
      usage = usage//'  '//new_line('a')//prefd//repeat(' ',4)//trim(adjustl(self%help))
      if (self%help_markdown/='') then
        usage = usage//trim(adjustl(self%help_markdown))
      endif
    else
      usage = usage//new_line('a')//prefd//repeat(' ', indent)//trim(adjustl(self%help))
    endif
  else
    usage = ''
  endif
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction usage
All Procedures
add add add_group assert_close_r32 assert_close_r32_1 assert_close_r64 assert_close_r64_1 assert_equal_i16 assert_equal_i16_1 assert_equal_i32 assert_equal_i32_1 assert_equal_i64 assert_equal_i64_1 assert_equal_i8 assert_equal_i8_1 assert_equal_l assert_equal_l_1 assert_equal_r32 assert_equal_r32_1 assert_equal_r64 assert_equal_r64_1 assert_positive_i16 assert_positive_i16_1 assert_positive_i32 assert_positive_i32_1 assert_positive_i64 assert_positive_i64_1 assert_positive_i8 assert_positive_i8_1 assert_positive_r32 assert_positive_r32_1 assert_positive_r64 assert_positive_r64_1 assign_object bctoi_I1P bctoi_I2P bctoi_I4P bctoi_I8P bcton bctor_R16P bctor_R4P bctor_R8P bit_size bit_size bit_size_chr bit_size_R16P bit_size_R4P bit_size_R8P bstr bstr_I1P bstr_I2P bstr_I4P bstr_I8P bstr_R16P bstr_R4P bstr_R8P byte_size byte_size_chr byte_size_I1P byte_size_I2P byte_size_I4P byte_size_I8P byte_size_R16P byte_size_R4P byte_size_R8P check check check check_action_consistency check_choices check_endian check_envvar_consistency check_list_size check_m_exclude_consistency check_m_exclusive check_m_exclusive check_named_consistency check_optional_consistency check_positional_consistency cla_assign_cla clasg_assign_clasg cli_assign_cli compact_real_string count count_substring ctoi_I1P ctoi_I2P ctoi_I4P ctoi_I8P cton ctor_R16P ctor_R4P ctor_R8P digit digit_I1 digit_I2 digit_I4 digit_I8 errored errored errored fake_call finalize finalize finalize free free free free_object get_args_from_invocation get_args_from_string get_cla get_cla get_cla_from_buffer get_cla_list get_cla_list get_cla_list_from_buffer get_cla_list_varying_char get_cla_list_varying_char get_cla_list_varying_I1P get_cla_list_varying_I1P get_cla_list_varying_I2P get_cla_list_varying_I2P get_cla_list_varying_I4P get_cla_list_varying_I4P get_cla_list_varying_I8P get_cla_list_varying_I8P get_cla_list_varying_logical get_cla_list_varying_logical get_cla_list_varying_R16P get_cla_list_varying_R16P get_cla_list_varying_R4P get_cla_list_varying_R4P get_cla_list_varying_R8P get_cla_list_varying_R8P get_clasg_indexes init init is_called_group is_defined is_defined is_defined_group is_parsed is_passed is_passed is_required_passed is_required_passed parse parse penf_init penf_print print print_error_message print_usage print_version raise_error_m_exclude raise_error_m_exclude raise_error_nargs_insufficient raise_error_switch_unknown raise_error_value_missing replace replace_all sanitize_defaults sanitize_defaults save_man_page save_usage_to_markdown set_mutually_exclusive_groups signature signature signature str str_a_I1P str_a_I2P str_a_I4P str_a_I8P str_a_R16P str_a_R4P str_a_R8P str_bol str_I1P str_I2P str_I4P str_I8P str_R16P str_R4P str_R8P strf_I1P strf_I2P strf_I4P strf_I8P strf_R16P strf_R4P strf_R8P strz strz_I1P strz_I2P strz_I4P strz_I8P tokenize unique upper_case usage usage usage wstrip
Call graph
usage calls replace_all, cton, str
replace_all calls wstrip, replace
cton calls ctoi_i1p, ctoi_i8p, ctor_r4p, ctoi_i4p, ctoi_i2p, ctor_r8p
str calls str_r4p, str_r8p, str_a_r8p, str_a_r4p, str_i8p, strf_r8p, str_i1p, str_a_i1p, str_bol, strf_r4p, str_a_i2p, strf_i4p, str_a_i8p, strf_i1p, str_a_i4p, str_i2p, strf_i8p, str_i4p, strf_i2p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
str_a_r8p calls str_r8p
str_a_r4p calls str_r4p
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i8p calls str_i8p
str_a_i4p calls str_i4p