compact_real – FLAP
compact_real Program
16 statements
Source File
Uses:
penf
iso_fortran_env
PENF's testing program.
Calls
Variables
test_passed
Source Code
compact_real
Variables
Type Attributes Name Initial
logical :: test_passed(3)
List of passed tests.
Source Code
program compact_real
!-----------------------------------------------------------------------------------------------------------------------------------
!< PENF's testing program.
!-----------------------------------------------------------------------------------------------------------------------------------
use penf
use, intrinsic :: ISO_FORTRAN_ENV, only : stdout=>OUTPUT_UNIT
!-----------------------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------------------
implicit none
logical :: test_passed(3) !< List of passed tests.
!-----------------------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------------------
call penf_init
test_passed = .false.
test_passed(1) = trim(str(n=1._R8P, compact=.true.))=='+0.1E+1'
print "(A,L1)", 'Compact 1.0: '//trim(str(n=1._R8P, compact=.true.))//', is correct? ', test_passed(1)
test_passed(2) = trim(str(n=1._R4P/3._R4P, compact=.true.))=='+0.333333E+0'
print "(A,L1)", 'Compact 1.0/3.0: '//trim(str(n=1._R4P/3._R4P, compact=.true.))//', is correct? ', test_passed(2)
test_passed(3) = trim(str(n=1._R16P/4._R16P, compact=.true.))=='+0.25E+0'
print "(A,L1)", 'Compact 1.0/4.0: '//trim(str(n=1._R16P/4._R16P, compact=.true.))//', is correct? ', test_passed(3)
write(stdout, "(A,L1)") new_line('a')//'Are all tests passed? ', all(test_passed)
stop
!-----------------------------------------------------------------------------------------------------------------------------------
endprogram compact_real
All Programs
compact_real face_test_basic face_test_colors face_test_styles flap_test_ansi_color_style flap_test_basic flap_test_choices_logical flap_test_group flap_test_hidden flap_test_minimal flap_test_nested flap_test_string test_all test_tester_1 test_tester_2 test_tester_3 test_tester_4
Call graph
compact_real calls penf_init, str
penf_init calls check_endian
str calls str_r8p, str_a_r8p, strf_r8p, str_a_i8p, strf_r4p, str_bol, str_i8p, str_i4p, strf_i2p, str_i1p, str_a_i4p, str_a_r4p, str_i2p, str_r4p, strf_i4p, str_a_i1p, str_a_i2p, strf_i1p, strf_i8p
str_r8p calls compact_real_string
str_a_r8p calls str_r8p
str_a_i8p calls str_i8p
str_a_i4p calls str_i4p
str_a_r4p calls str_r4p
str_r4p calls compact_real_string
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p