flap_test_choices_logical – FLAP
flap_test_choices_logical Program
13 statements
Source File
Uses:
flap
penf
Test FLAP for bad usage of choices option with logical
Calls
Variables
cli vbval error
Source Code
flap_test_choices_logical
Variables
Type Attributes Name Initial
type(command_line_interface) :: cli
Command Line Interface (CLI).
logical :: vbval
Valued-boolean value.
integer(kind=I4P) :: error
Error trapping flag.
Source Code
program flap_test_choices_logical
!< Test FLAP for bad usage of choices option with logical
use flap, only : command_line_interface
use penf
implicit none
type(command_line_interface) :: cli   !< Command Line Interface (CLI).
logical                      :: vbval !< Valued-boolean value.
integer(I4P)                 :: error !< Error trapping flag.
call cli%init(progname='test_choices_logical')
call cli%add(switch='--boolean-value', switch_ab='-bv', help='A help message', &
             required=.false., def='.false.', choices='.True.,.False.', act='store', error=error)
call cli%parse(error=error)
call cli%get(switch='-bv', val=vbval, error=error)
print "(A)", "Error code: "//trim(str(error, .true.))
endprogram flap_test_choices_logical
All Programs
compact_real face_test_basic face_test_colors face_test_styles flap_test_ansi_color_style flap_test_basic flap_test_choices_logical flap_test_group flap_test_hidden flap_test_minimal flap_test_nested flap_test_string test_all test_tester_1 test_tester_2 test_tester_3 test_tester_4
Call graph
flap_test_choices_logical calls str
str calls strf_r8p, strf_i2p, strf_r4p, str_i8p, str_a_i8p, strf_i1p, str_a_i2p, str_i1p, str_bol, str_r4p, str_i4p, strf_i4p, str_a_r8p, str_a_i4p, str_a_i1p, str_a_r4p, str_i2p, str_r8p, strf_i8p
str_a_i8p calls str_i8p
str_a_i2p calls str_i2p
str_r4p calls compact_real_string
str_a_r8p calls str_r8p
str_a_i4p calls str_i4p
str_a_i1p calls str_i1p
str_a_r4p calls str_r4p
str_r8p calls compact_real_string