Test_Driver – FLAP
Test_Driver Program
Source File
Uses:
IR_Precision
iso_fortran_env
Testing program for IR_Precision, Pure Fortran (2003+) library for ensuring codes portability
Usage
 ./Test_Driver
Calls
Source Code
program Test_Driver
!-----------------------------------------------------------------------------------------------------------------------------------
!< Testing program for IR_Precision, Pure Fortran (2003+) library for ensuring codes portability
!<
!<### Usage
!<```bash
!< ./Test_Driver
!<```
!-----------------------------------------------------------------------------------------------------------------------------------
USE IR_Precision
USE, intrinsic:: ISO_FORTRAN_ENV, only: stdout=>OUTPUT_UNIT
!-----------------------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------------------
implicit none
!-----------------------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------------------
! initialize IR_Precision
call IR_Init
! print main IR_Precision values
call IR_Print(unit=stdout)
print "(A)", ''
print "(A)", 'Testing IR_Precision tools'
print "(A)", 'Casting real-to-string: '//str(n=1._R8P)
print "(A)", 'Casting integer-to-string: '//str(n=11_I8P)
print "(A,"//FR8P//")", 'Casting string-to-real: ',cton(str='2.2d0',knd=1._R8P)
print "(A,"//FI4P//")", 'Casting integer-to-string: ',cton(str='43',knd=1_I4P)
print "(A)", 'Casting integer-to-string with zero padding: '//trim(strz(nz_pad=3,n=34_I8P))
! print "(A)", 'Casting real-to-bit_string: '//bstr(n=1._R4P)
print "(A)", 'Casting integer-to-bit_string: '//bstr(n=1_I4P)
! print "(A,"//FR4P//")", 'Casting bit_string-to-real: ',bcton(bstr='00111111100000000000000000000000',knd=1._R4P)
print "(A,"//FI4P//")", 'Casting bit_string-to-integer: ',bcton(bstr='00000000000000000000000000000001',knd=1_I4P)
print "(A)", 'Number of digit of 1023: '//str(n=digit(1023_I4P))
stop
!-----------------------------------------------------------------------------------------------------------------------------------
endprogram Test_Driver
Call graph
test_driver calls digit, strz, bstr, cton, str, ir_init, bcton, ir_print
digit calls digit_i2, digit_i1, digit_i8, digit_i4
strz calls strz_i8p, strz_i1p, strz_i2p, strz_i4p
bstr calls bstr_i2p, bstr_i1p, bstr_r4p, bstr_i8p, bstr_i4p, bstr_r8p
cton calls ctoi_i1p, ctoi_i8p, ctor_r8p, ctoi_i2p, ctoi_i4p, ctor_r4p
str calls str_a_i2p, strf_r8p, str_a_i1p, str_i8p, strf_i8p, str_i4p, str_a_r4p, strf_r4p, str_a_i4p, str_i2p, strf_i2p, strf_i1p, str_i1p, str_r4p, str_a_r8p, strf_i4p, str_bol, str_a_i8p, str_r8p
ir_init calls check_endian
bcton calls bctoi_i8p, bctoi_i4p, bctor_r4p, bctoi_i2p, bctoi_i1p, bctor_r8p
str_a_i2p calls str_i2p
str_a_i1p calls str_i1p
str_a_r4p calls str_r4p
str_a_i4p calls str_i4p
str_a_r8p calls str_r8p
str_a_i8p calls str_i8p
check_endian calls is_little_endian
bctoi_i8p calls str
bctoi_i4p calls str
bctor_r4p calls str
bctoi_i2p calls str
bctoi_i1p calls str
bctor_r8p calls str