test_hidden – FLAP
test_hidden Program
28 statements
Source File
Uses:
flap
penf
A testing program for FLAP, Fortran command Line Arguments Parser for poor people
Compile
See compile instructions.
Usage Compile
See usage instructions.
Calls
Variables
cli a_string g_string a_integer error
Source Code
test_hidden
Variables
Type Attributes Name Initial
type(command_line_interface) :: cli
Command Line Interface (CLI).
character(len=99) :: a_string
String value.
character(len=99) :: g_string
Ghost string value.
integer(kind=I4P) :: a_integer
Integer value.
integer(kind=I4P) :: error
Error trapping flag.
Source Code
program test_hidden
!< A testing program for FLAP, Fortran command Line Arguments Parser for poor people
!<
!<### Compile
!< See [compile instructions](https://github.com/szaghi/FLAP/wiki/Download-compile).
!<
!<###Usage Compile
!< See [usage instructions](https://github.com/szaghi/FLAP/wiki/Testing-Programs).
!-----------------------------------------------------------------------------------------------------------------------------------
use flap, only : command_line_interface
use penf
!-----------------------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------------------
implicit none
type(command_line_interface) :: cli       !< Command Line Interface (CLI).
character(99)                :: a_string  !< String value.
character(99)                :: g_string  !< Ghost string value.
integer(I4P)                 :: a_integer !< Integer value.
integer(I4P)                 :: error     !< Error trapping flag.
!-----------------------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------------------
call cli%init(description = 'hiddens usage FLAP example')
call cli%add(switch='--string', switch_ab='-s', help='a string', required=.true., act='store', error=error) ; if (error/=0) stop
call cli%add(switch='--hidden', switch_ab='-hi', help='ghost string', required=.false., def='gstring not passed', &
             hidden=.true., act='store', error=error) ; if (error/=0) stop
call cli%add(switch='--integer', switch_ab='-i', help='a integer', required=.true., act='store', error=error) ; if (error/=0) stop
call cli%get(switch='-s', val=a_string, error=error) ; if (error/=0) stop
call cli%get(switch='-hi', val=g_string, error=error) ; if (error/=0) stop
call cli%get(switch='-i', val=a_integer, error=error) ; if (error/=0) stop
print '(A)', cli%progname//' has been called with the following argument:'
print '(A)', 'String       = '//trim(adjustl(a_string))
print '(A)', 'Ghost string = '//trim(adjustl(g_string))
print '(A)', 'Integer      = '//trim(adjustl(str(a_integer, .true.)))
stop
!-----------------------------------------------------------------------------------------------------------------------------------
endprogram test_hidden
All Programs
compact_real test_all test_basic test_choices_logical test_group test_hidden test_minimal test_nested test_string test_tester_1 test_tester_2 test_tester_3 test_tester_4
Call graph
test_hidden calls str
str calls str_a_i8p, strf_i8p, str_a_i2p, str_r4p, str_a_i4p, str_i1p, strf_i1p, str_a_r8p, strf_r4p, str_a_i1p, strf_i2p, str_r8p, str_i8p, str_i4p, strf_r8p, str_a_r4p, str_bol, str_i2p, strf_i4p
str_a_i8p calls str_i8p
str_a_i2p calls str_i2p
str_r4p calls compact_real_string
str_a_i4p calls str_i4p
str_a_r8p calls str_r8p
str_a_i1p calls str_i1p
str_r8p calls compact_real_string
str_a_r4p calls str_r4p